apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: myminio
  namespace: minio-tenant-1
spec:
  image: minio/minio:RELEASE.2023-11-20T22-40-07Z
  imagePullPolicy: IfNotPresent
  pools:
    - servers: 4
      volumesPerServer: 4
      size: 10Gi
      storageClassName: standard
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
  mountPath: /export
  requestAutoCert: true
  features:
    bucketDNS: false
    domains:
      - minio.example.com
